### ISSUE TITLE
Dude, the logo is terrible!

### ISSUE THREAD

**Issue by djc** [djc/couchdb-python#126]
_From [italo.maia@gmail.com](https://code.google.com/u/italo.maia@gmail.com/) on May 12, 2010 16:37:09_

What steps will reproduce the problem? 1.Open the google page
2.Get horrified!!! What is the expected output? What do you see instead? A nice logo. It seems like the python logo is doing "service" to the guy in
the couch! @.@ Gee

_Original issue: http://code.google.com/p/couchdb-python/issues/detail?id=126_

**Comment by italomaia** [comment]
This issue is still open. Is this correct? Is there anything else missing?

**Comment by djc** [comment]
It's still open, but at this point it's sort of moot, since the project currently doesn't any logo anywhere. Thank you for your contributions, but I think I'll just close this.
