### ISSUE TITLE
Database.view() and list() don't work on Google's AppEngine

### ISSUE THREAD

**Issue by djc** [djc/couchdb-python#224]
_From [alexan...@codjovi.fr](https://code.google.com/u/113203882735910317882/) on May 20, 2013 21:11:41_

What steps will reproduce the problem? 1. setup a python appengine env
2. use the list() or view() functions 3. What is the expected output? What do you see instead? The script get stuck on list() (or when you want iterate the result of view())

I think it is getting stuck on conn.getresponse() in http._try_request() What version of the product are you using? On what operating system? 0.9 Please provide any additional information below.

_Original issue: http://code.google.com/p/couchdb-python/issues/detail?id=224_

**Comment by Philoozushi** [comment]
So I think alexan...@codjovi.fr is very right.
I updated their fix to the current implementation, and here is my suggestion now :

`http.py` line 160
```python
    def close(self):
        while not self.resp.isclosed():
            chunk =  self.resp.read(CHUNK_SIZE)
            if len(chunk) == 0:
                self.resp.close()
        if self.conn:
            self._release_conn()
```
It works well for me.
@djc could you check this and merge if it looks good to you?

**Comment by djc** [comment]
Looks good to me! Instead of `len(chunk) == 0`, just write `chunk`, and do a PR. Thanks!

**Comment by Philoozushi** [comment]
PR sent, thanks! :)
