### ISSUE TITLE
Change the http implementation to requests lib

### ISSUE THREAD

**Issue by the-destro** [djc/couchdb-python#262]
I was wondering if you would be open to a conversion to using requests as it would allow most of the http module to be removed, greatly simplifying that module. I am away of py-couchdb but there are other changes to the api that I do not enjoy and I also prefer using the mapping part of the library. I am willing to help with this conversion.

**Comment by kxepal** [comment]
I think this could be good, but if `requests` library support will be optional and pluggable as like as couchdb-python supports different json libraries. In the same way curl based backend could be added as like as any others. Why not?

Just moving to requests library turns couchdb-python into yet another CouchDB client based on requests, just with different API and feature set out of the box. Boring (:

**Comment by kxepal** [comment]
IIRC there was a couchdb-python fork on google code which used curl instead of http module for performance reasons.

**Comment by henridwyer** [comment]
I just wanted to restart this conversation - what would the disadvantage of just using requests be? It seems a bit out of scope for this package to reimplement those functionalities.

**Comment by djc** [comment]
First disadvantage: changing CouchDB-Python now is a bunch of work, with benefits which seem unclear to me. Second disadvantage: one more dependency (which itself has dependencies, and/or bundles a bunch of stuff) makes CouchDB-Python more heavyweight in deployment.

This package is very much a thin layer around a HTTP API. As such, I don't consider the HTTP bits to be out of scope. Anyway, if you're interested in contributing an alternative implementation of the `couchdb.http` module that can pass the tests, I'd be happy to bundle that as something people can optionally enable!
