### ISSUE TITLE
documentation does not tell you how to pass credentials

### ISSUE THREAD

**Issue by snowch** [djc/couchdb-python#263]
Maybe it's in the docs, but I couldn't see how you pass your credentials to couchdb.

I eventually found out using google, but this info should probably be in the docs?

**Comment by Tamriel** [comment]
You said you found out how to do it. Can you share that information?
I think about switching to https://py-couchdb.readthedocs.org/.

**Comment by djc** [comment]
The statement on that package's homepage that others are not maintained is incorrect. CouchDB-Python is maintained just fine (but not much development is otherwise happening).

IIRC you can just pass the authentication data in the URL, http://user:pass@host:port/.

**Comment by Tamriel** [comment]
Thanks for the fast answer. Yes, that works :)
Without SSL it is not safe to use over internet, right?

**Comment by djc** [comment]
That's right. I guess you could possibly use [OAuth authentication](#oauth-authentication) in that case, but it's a bit more complex.

**Comment by Tamriel** [comment]
Is SSL possible with couchdb-python?

**Comment by djc** [comment]
I've never tried it, but I don't know why it wouldn't work. Let's put it like this: you're welkom to file bugs if it breaks.

**Comment by kxepal** [comment]
@Tamriel couchdb-python works fine with SSL.
