### ISSUE TITLE
TypeError: string indices must be integers, not str

### ISSUE THREAD

**Issue by gcwarner1** [djc/couchdb-python#266]
The code:

    auth = couchdb.Session()
    auth.name = 'name'
    auth.password = 'password'
    s = couchdb.Server('address',session=auth)

    transformdb_dict = {
        "subject_id" : "TEST",
        "project" : "TRANSFORM-DBS",
        "study" : "MRI",
        "tasks" : "tasks",
        "session" : "session_num",
        "run" : "run_num",
        "data_type" : "DICOM",
        "file_path" : "TRANSFORM-DB/MRI/",
        "data_comment" : "",
        "data_quality_rating" : "",
        "data_logger_email" : "args.r",
        "data_registration_datatime" : "registration_time",
        "type" : "data"
        }

    json = json.dumps(transformdb_dict)
    transformdb_db = s["transformdb"]
    transformdb_db.save(json)

Is returning the following error:

    Traceback (most recent call last):
      File "test.py", line 26, in <module>
        transformdb_db.save(json)
      File "/space/jazz/1/users/gwarner/anaconda/lib/python2.7/site-packages/couchdb/client.py", line 429, in save
    func = _doc_resource(self.resource, doc['_id']).put_json
    TypeError: string indices must be integers, not str

My understanding was that the `save` function generated the document ID unless specified otherwise yet the traceback suggests that it is looking for the ID as a necessary field. Why is this? The objective of this script is to save the json file defined by transformdb_dict to the transformdb database.

**Comment by kxepal** [comment]
`couchdb-python` also handles all necessary json serialization for you so `json = json.dumps(transformdb_dict)` is redundant.

**Comment by djc** [comment]
To answer your question more directly, the code in the traceback is only executed if `'_id'` is in the document. Because you already encoded your document as JSON, it triggers on the string (e.g. in `subject_id`), but then fails because it cannot refer to the `_id` key in the object. Closing.

**Comment by gcwarner1** [comment]
Ah, that makes sense. Thank you both.
