### ISSUE TITLE
How to use couchdb-replicate script?

### ISSUE THREAD

**Issue by ktarasz** [djc/couchdb-python#269]
Whatever I tried, I got:
>  ... does not appear to be a CouchDB

Exapmles:
```
$ couchdb-replicate http://localhost:9000/db1 http://localhost:9000/db2
Usage: couchdb-replicate [options] <source> <target>

couchdb-replicate: error: 'http://localhost:9000/db1' does not appear to be a CouchDB

```

CouchDB work on port 9000 with the database "db1"

**Comment by djc** [comment]
Hey, sorry you ran into this! I did some initial playing around with the code to see if I could figure out the problem, but so far I haven't been successful. :disappointed: If you want to do some experimenting, that might be helpful. The error comes from the `findpath()` function, here:

https://github.com/djc/couchdb-python/blob/master/couchdb/tools/replicate.py#L26

It also seems to fail a trivial test case on my system, so it seems likely that something has gone astray, but it would take some digging to figure out what. I'll try to pick that up later if you are unable to get to it.

**Comment by djc** [comment]
Sorry it took me so long to get to this. Anyway, it seems to work for me now!
