### ISSUE TITLE
Unable to retrieve original JSON

### ISSUE THREAD

**Issue by officialpatterson** [djc/couchdb-python#272]
Accusing my database using db.iterview(...), Im able to get the id, revision, and as a whole, but unable to retrieve the original JSON that was posted. 

Is this lack of functionality missing or have I missed something?

**Comment by djc** [comment]
If you mean the JSON that the database returns for the view requests, no, that's not accessible from the API. What's your use case, exactly? Of course you could duplicate the function, it's not a lot of code.

**Comment by officialpatterson** [comment]
I'm currently moving data from couchdb to AWS elastic search and so the ID and revision are not needed for the ES instance but I do need the raw JSON which I added to couchdb

**Comment by djc** [comment]
Ah! Well, I think you might not fully understand how the view API works.

Views don't always (and in fact, often don't) return the actual documents. Are you using the `_all_docs` view? In any case, if you provide the `include_docs` option, the resulting `Row` object should have a `doc` attribute containing the original document.

Hope that helps!

**Comment by officialpatterson** [comment]
I do use the all docs view and include docs parameter but it includes the document inside angled brackets along with the ID and revision

**Comment by djc** [comment]
Well, yes, the `Document` class has some niceties to pretty-print it. However, you can trivially use `dict(doc.items())` to get a normal Python dictionary (JSON encoding doc works, too).
