### ISSUE TITLE
Docs wrapped by _wrap_row from a view cannot be deleted, KeyError

### ISSUE THREAD

**Issue by rubendibattista** [djc/couchdb-python#278]
import couchdb
    from couchdb.mapping import Document

    db = couchdb.Server().create('test')
    mydoc = Document()
    mydoc.store(db)
      
    docs = db.view('_all_docs', wrapper=Document._wrap_row)
    mydoc_ = docs.rows[0]
    db.delete(mydoc)

Raises `KeyError: '_rev' `

The easiest solution I found is ([mappings.py](https://github.com/djc/couchdb-python/blob/master/couchdb/mapping.py#L402)):
```
    @classmethod
    def _wrap_row(cls, row):
        doc = row.get('doc')
        if doc is not None:
            return cls.wrap(doc)
        data = row['value']
        data['_id'] = row['id']
        data['_rev'] = data['rev']  # <=====
        return cls.wrap(data)
```

even if it seems a bit hacky. 
Is this an intended behaviour?

**Comment by djc** [comment]
That seems like a totally sane fix. Do you want to submit a pull request, ideally with a quick unit test for this?

**Comment by rubendibattista** [comment]
@djc Ok! I will do as soon as possible. :)

**Comment by djc** [comment]
@rubendibattista did you have a chance to look at this?

**Comment by rubendibattista** [comment]
@djc The proposed solution breaks other two unittests in the `couchdb.mappings` module. I hadn't chanche to see which is the problem there. I'll work on that as I can ;)
