### ISSUE TITLE
TypeError: 'ResponseBody' object is not subscriptable

### ISSUE THREAD

**Issue by guyskk** [djc/couchdb-python#281]
I use db.save(doc),  it cause error sometimes:
``` 
File "/usr/lib/python3.5/site-packages/couchdb/client.py", line 440, in save
    id, rev = data['id'], data.get('rev')
TypeError: 'ResponseBody' object is not subscriptable
```

and I try to find the reason, in http.py:
```
369  	        # Buffer small non-JSON response bodies
370  	        elif int(resp.getheader('content-length', sys.maxsize)) < CHUNK_SIZE:
371  	            data = resp.read()
372  	            self.connection_pool.release(url, conn)
373  	
374  	        # For large or chunked response bodies, do not buffer the full body,
375  	        # and instead return a minimal file-like object
376  	        else:
377 B->	            data = ResponseBody(resp, self.connection_pool, url, conn)
378  	            streamed = True
```

when resp's content-length > CHUNK_SIZE, it will cause error.

**Comment by djc** [comment]
This needs a bit more detail. I don't think library code is passing a `ResponseBody` straight into `db.save()`. Can you create a reduced test case from your code that demonstrates the problem?

**Comment by guyskk** [comment]
It seems caused by unicode _id, not caused by large data:

```
def test_save_unicode(self):
    doc = {'_id': '关闭'}
    id, rev = self.db.save(doc)
    doc2 = self.db.get(id)
    id2, rev2 = self.db.save(doc2)
    self.assertTrue(doc['_id'] == id)
    self.assertTrue(doc['_id'] == id2)
```

`self.db.save(doc2)` will raise exception, and I just only find `{'_id': '关闭'}` will cause exception.
```
>>> '关闭'.encode('utf-8')
b'\xe5\x85\xb3\xe9\x97\xad'
>>>
```

**Comment by guyskk** [comment]
it's not really possible for us to resolve the problem
https://github.com/kennethreitz/requests/issues/3098

**Comment by djc** [comment]
Thanks for working that out. I've filed https://issues.apache.org/jira/browse/COUCHDB-3003 and will close this bug for now.
