### ISSUE TITLE
Changes feed does not work with couchbase sync gateway

### ISSUE THREAD

**Issue by hermitdemschoenenleben** [djc/couchdb-python#290]
In Couchbase sync gateway's changes feed, chunks don't necessarily correspond to documents, i.e. a JSON object can be truncated. However, couchdb-python calls iterchunks() and tries do decode each single element using JSON which obviously will fail as the JSON object may be truncated.
In order to fix this, I created a quick fix:
https://github.com/djc/couchdb-python/pull/289/commits/25b164e547673de3807a42e7ee0793dfbaf57844
The new iterdocs method tries to decode each chunk, if this fails due to truncation, the current line is saved in a buffer and decoding is retried once the next chunk is there.

However, this is probably not the best / most elegant way to do this.

**Comment by hermitdemschoenenleben** [comment]
aiocouchdb apparently had the same issue, was fixed like this: https://github.com/aio-libs/aiocouchdb/commit/6e63d05ce7131feb4f15df31d63d3265d1d34504

**Comment by djc** [comment]
Fixed in #289.
