### ISSUE TITLE
HTTP basic auth is broken for accented characters

### ISSUE THREAD

**Issue by adrienverge** [djc/couchdb-python#301]
Username/password encoding in HTTP basic auth is currently broken for non-ASCII password.

Example with user `user` and password `unusual-char-é`. With curl it works as expected:

```shell
curl -v 'http://user:unusual-char-%C3%A9@localhost:5984/'
```

```
> GET / HTTP/1.1
> Authorization: Basic YWxpY2U6YWRyaWVuPTohw6k=
> 
< HTTP/1.1 200 OK
```

But with couchdb-python the string is decoded from `utf-8` then re-encoded into `latin1`, causing an incorrect Authorization header:

```python
url = 'http://user:unusual-char-%C3%A9@localhost:5984/'
couchdb.Server(url).version()
```

```
> GET / HTTP/1.1
> Authorization: Basic dXNlcjp1bnVzdWFsLWNoYXIt6Q==
> 
< HTTP/1.1 401 Unauthorized
```

**Comment by kxepal** [comment]
FYI: It's only since [RFC-7617](http://tools.ietf.org/html/rfc7617) utf-8 basic auth credentials became officially legal. Previously, RFC-2616 only allowed to use ISO-8859-1 which is basically latin1.

**Comment by adrienverge** [comment]
Hey @kxepal, I didn't know, thanks! It's quite recent...

Still, I think python-couchdb should support it. I made a pull-request for this.
