### ISSUE TITLE
View Server Write Error: str, not bytes

### ISSUE THREAD

**Issue by geppettodivacin** [djc/couchdb-python#319]
I'd been having difficulty connecting the view server with CouchDB, as the view server died before it sent a response. The logs produced the following lines again and again:

```
[2017-05-24 15:14:03,749] [ERROR] Error: write() argument must be str, not bytes
Traceback (most recent call last):
  File "c:\...\couchdb\view.py", line 164, in run
    _writejson(retval)
  File "c:\...\couchdb\view.py", line 55, in _writejson
    output.write(obj)
TypeError: write() argument must be str, not bytes
```

It appears that the write function no longer accepts bytes objects. I'm not sure when this change was made, but it's more recent than 2.7 and at least as recent as 3.5.

I verified that this was the only problem by wrapping the output stream with a class to redefine write. It works fine after this change. (Probably not the prettiest solution, but it works!)

```python
class betterout():
    def __init__(self, out):
        self.out = out

    def __getattr__(self, attr):
        if attr == 'write':
            return self.write
        else:
            return getattr(self.out, attr)

    def write(self, text, *args, **kwargs):
        if isinstance(text, str):
            self.out.write(text, *args, **kwargs)
        else:
            self.out.write(text.decode('utf-8'), *args, **kwargs)
```

Has anyone else run into this problem? Is there a more standard solution to the problem?

**Comment by djc** [comment]
Can you check if #320 resolves your problem?

It would also be great if you can contribute a test case that triggers this problem.

**Comment by geppettodivacin** [comment]
Yes, this patch fixes the error. Thank you.

Prior, any retrieval from a Python view document induces this error. For example:

```python
db = couchdb.Server()['mydb']
def map_fun(doc):
    yield 1, 2
view = ViewDefinition('example', 'example', map_fun, language='python')
view.sync(db)
rows = db.view('example/example')
for row in rows:
    print(row)
# This never returns, as CouchDB repeatedly tries to connect,
# but the view server dies and sends no error information.
# The view server logs the error above repeatedly as it respawns
# and dies.
```

The lack of error information is a different issue that may already have mention here. I'll post my own if I can't find one then write a PR for that when I get home this evening.

This issue can be closed when you deem it complete. Thank you.

**Comment by djc** [comment]
Good, thanks for testing!
