### ISSUE TITLE
missing find() definition on Database class

### ISSUE THREAD

**Issue by ycbayrak** [djc/couchdb-python#325]
When `pip install couchdb` on python3.5 package comes without `find()` method.

**Comment by djc** [comment]
That's right; currently, there's no released version containing `find()` yet. I'll see if I can make a release soon.

**Comment by ycbayrak** [comment]
Okey. Thanks.

**Comment by pts-sergiomartins** [comment]
I'm hoping to get my hands on this too.
@djc is there something preventing a release? I'm happy to lend a hand

**Comment by djc** [comment]
@pts-sergiomartins just my lack of time. I've released 1.2 now, thanks for the ping.

**Comment by pts-sergiomartins** [comment]
Thanks very much ^_^
