### ISSUE TITLE
Cant find a way to send headers in replication

### ISSUE THREAD

**Issue by ngrj** [djc/couchdb-python#328]
Hi,  
I need to send headers while making a replication requests, I can do it using curl as mentioned [here](https://wiki.apache.org/couchdb/Replication#Username_Workaround_.28older_CouchDBs_only.29). This method does not work with current couchdb python replicate function, is there a work around it ?

**Comment by djc** [comment]
Thanks for reporting this. Unfortunately I no longer have time to spend on CouchDB-Python, so until someone else steps up to maintain it, there will not be a fix for this.

**Comment by ngrj** [comment]
okay, thanks a lot for your work.
